function Comp = addComponents2Panel_D2(hPanel)

global hFig

data = guidata(hFig); 
 
h_Gap = 0.025; 
h_Info = 0.8;

nB = 2;
h_Button = (1-h_Gap*(nB+2)-h_Info)/nB;

h_Button = 0.2;

BC_PB = data.Color.BC_PB;

% Patient button
% y = 1 - h_Gap - h_Button;
Comp.Pushbutton.LoadImage = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Load 2D',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 0.7 0.6 h_Button], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_D2Panel_LoadImage);
                            
% % image info
% y = y-h_Gap-h_Info;
% % Comp.hPanel.ImageInfo = uipanel('parent', hPanel,...
% %                                 'Unit', 'Normalized',...
% %                                 'Position', [.0, y, 1, h_Info], ...
% %                                 'Title', '',...
% %                                 'FontSize',                 10,...
% %                                 'Units',                     'normalized', ...
% %                                 'visible',                      'on', ...
% %                                 'ForegroundColor',       'white',...
% %                                 'BackgroundColor',       'black', ...
% %                                 'HighlightColor',          'k',...
% %                                 'ShadowColor',            'k');
% 
% ColumnName =  [];
% RowName = [];
% 
% Comp.Table.Date = uitable('parent', hPanel,...
%                                            'Units', 'normalized', ...
%                                            'Position', [.0, y, 1, h_Info],...
%                                              'ForegroundColor',         [1 1 1],...
%                                             'BackgroundColor',         [0 0 0],...
%                                             'ColumnName',               ColumnName,...
%                                             'Columnwidth',                {30 150 40},...
%                                             'ColumnFormat',             {'logical', 'char', 'char'},...
%                                             'ColumnEditable',            [true false false], ...
%                                             'RowName',                     RowName, ...
%                                             'FontSize',                       10);
% %                                         , ....
% %                                             'CellSelectionCallback',    @Callback2_PatientPanel_DateTable);
%                                         
% % Patient button
% y = y - h_Gap - h_Button;
% Comp.Pushbutton.LoadImage = uicontrol('parent', hPanel, ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Load  Images',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0.15 y 0.7 h_Button], ...
%                                 'FontSize', 12, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Callback', @Callback_Pushbutton_PatientPanel_LoadImage);
% 
%                             
%                             nR = 3;
% txt.FirstRow = {'Name', 'Value'};
% txt.FirstColumn = {'FoV'; 'Image Size'; 'Pixel Size'};
% columnRatio = [1]; % width ratio to first column
% txt.DataStr = {'350'; ''; ''};
% FS = 10;
% 
% % [Comp.hEdit.ImageInfo] = fun_myTable(Comp.hPanel.ImageInfo, nR, columnRatio, txt, FS);