function Comp = addComponents2Panel_SagitalView(hPanel)

FC = [255 255 102]/255;

% axes
Comp.hAxis.Image = axes('Parent',                   hPanel, ...
                            'color',        'none',...
                            'xcolor', FC,...
                            'ycolor', FC, ...
                            'gridcolor',   FC,...
                            'Units',                    'normalized', ...
                            'HandleVisibility',     'callback', ...
                            'Position',                 [0.05 0.1 0.9 0.9]);

% Comp.hAxis.Image.XAxisLocation='top';
Comp.hAxis.Image.XLabel.String = 'y';
Comp.hAxis.Image.YLabel.String = 'z';
hold(Comp.hAxis.Image, 'on')