function Comp = addComponents2Panel_D2View(hPanel)

FC = [255 255 102]/255;

% axes
hA = axes('Parent',                   hPanel, ...
                            'color',        'none',...
                            'Units',                    'normalized', ...
                            'HandleVisibility',     'callback', ...
                            'Position',                 [0.05 0.05 0.9 0.9]);

% slice
hPlotObj.ID2 = imshow([], 'parent', hA);

% hPlotObj.xLine = images.roi.Line(hA, 'Position',[0, 0; 0, 0], 'Color', 'r', 'LineWidth', 1);
% addlistener(hPlotObj.xLine, 'MovingROI', @Callback_XHair_x);
% 
% hPlotObj.yLine = images.roi.Line(hA, 'Position',[0, 0; 0, 0], 'Color', 'g', 'LineWidth', 1);
% addlistener(hPlotObj.yLine, 'MovingROI', @Callback_XHair_yOnAxialView);

hold(hA, 'on')

% slider
Comp.hSlider.Slice = uicontrol('Parent',  hPanel,...
            'Style','slider',...
            'Units', 'normalized',...
            'Position',[0.95 0.1 0.025 0.8],...
            'BackgroundColor', 'b',...
            'ForegroundColor', 'w',...
            'Visible', 'on', ...
                'Callback', @Callback_Slider_D2ViewPanel_SliceSlider);


Comp.hAxis.Image = hA;
Comp.hPlotObj = hPlotObj;