function Panel = addPanel(hFig)

w1 = 0.15;
w2 = (1-w1)/2;
w3 = w2;

h11 = 0.5;
h12 = 0.3;
h13 = 1-h11-h12;
hAbout = 0.05;

h21 = 1/2;
h22 = h21;
h31 = h21;
h32 = h22;

%% Load image
Panel.Patient.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, h12+h13, w1, h11], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');



%% View
Panel.AxialView.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [w1, h22, w2, h21], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

Panel.CoronalView.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [w1, 0, w2, h22], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

Panel.SagitalView.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [w1+w2, 0, w3, h31], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');


                            % %% Contrast bar
% Panel.ContrastBar.hPanel = uipanel('parent', hFig,...
%                                 'Unit', 'Normalized',...
%                                 'Position', [w_Left, h_View, w_Middle, h_ContrastBar], ...
%                                 'Title', '',...
%                                 'FontSize',                 12,...
%                                 'Units',                     'normalized', ...
%                                 'visible',                      'on', ...
%                                 'ForegroundColor',       'k',...
%                                 'BackgroundColor',       'k', ...
%                                 'HighlightColor',          'c',...
%                                 'ShadowColor',            'k');
% 
% %% Slice slider
% Panel.SliceSlider.hPanel = uipanel('Parent',                    hFig,...    
%                                 'Title',                        '',...
%                                 'FontSize',                 12,...
%                                 'Units',                     'normalized', ...
%                                 'Position',                  [w_Left+w_Middle, 0, w_Right, 1],...
%                                     'visible',                      'on', ...
%                                 'ForegroundColor',       'w',...
%                                 'BackgroundColor',       'black', ...
%                                 'HighlightColor',          'c',...
%                                 'ShadowColor',            'black');
% 


                            
%% about
Panel.About.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 0., w1, hAbout], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'k',...
                                'ShadowColor',            'k');
                          